### ISSUE TITLE
Update darkwolfbootstrap 5.2 with all bugs detected until today and fixed

### ISSUE THREAD

**Issue by SteppenWolf68** [phpmyadmin/themes#78]
Hi @williamdes 

I upload .zip file with darkwolfbootstrap theme update for phpMyAdmin 5.2

The errors detected to date have been corrected in both theme.css and theme.rtl.css

I will appreciate your help to know if this theme is a candidate for https://www.phpmyadmin.net/themes

Thank you very much in advance, regards

[darkwolfbootstrap.zip](https://github.com/phpmyadmin/themes/files/9152186/darkwolfbootstrap.zip)

**Comment by williamdes** [comment]
Hi @SteppenWolf68
I have been very busy lately this is why I did not handle all the feedback on the themes repository

I think you/I can close https://github.com/phpmyadmin/themes/pull/75 since the zip attached replaces it

Let me know if you have the git CLI installed on your workstation and I will gide you on how to setup it for upload your changes
Meanwhile this zip will be uploaded here as soon as I can handle this (unzip&push into git)

**Comment by SteppenWolf68** [comment]
Hi @williamdes 

Don't worry, as soon as you have some free time and you can review the topic, I'll appreciate it.

Best regards

**Comment by Puigdemunt** [comment]
Hi SteppenWolf68
Thanks for the update, but horizontal scroll bar is not showing when you browse a table.

**Comment by InformatiqueProg** [comment]
Hi

@Puigdemunt is right, same problem on Edge and Chrome but works fine on Firefox

**Comment by SteppenWolf68** [comment]
Hi @Puigdemunt / @InformatiqueProg 

I'm so sorry I uploaded the wrong zip file.

Thanks for the feedback. I have updated the .zip attached above, I hope the problem is resolved.

best regards

**Comment by InformatiqueProg** [comment]
Hi @SteppenWolf68 

Always works on Firefox and now i have the horizontal scroll bar on Edge and Chrome
Thanks👍

**Comment by Puigdemunt** [comment]
WOW!
Thanks a lot @SteppenWolf68
