### ISSUE TITLE
Financial support for development

### ISSUE THREAD

**Issue by abolfazlrvn** [phpmyadmin/themes#93]
Hello friends,
phpMyAdmin is one of the most popular for database management. But it certainly has the potential to have many tools for ease of use.
Is there anyone who can provide financial support so that I can work on it professionally?

**Comment by ibennetch** [comment]
Hi,

In general, since this is an open source program many people will contribute as a way to give back to the community. Our core development team is formed of people who have taken a long-term interest in the project.

We are very fortunate that there have been quite a few theme developers who have volunteered their work to be shared with the community.

You may also be interested in reviewing https://www.phpmyadmin.net/contractor/
